stages:
  - build

before_script:
  - pwd

cache:
  paths:
    - vendor

build jar1:
  stage: build
  only:
    refs:
      - dev
  script:
    - sudo cp /data/conf/dcm-dev.conf conf/app.conf
    - sudo /usr/local/go/bin/go mod tidy
    - sudo /usr/local/go/bin/go mod vendor
    - sudo /usr/local/go/bin/go build -o dcm-api-dev -ldflags "-s -w"
    - sudo cp -f dcm-api-dev /data/runner/dcm/
    - sudo /data/sh/dcm/dcm-dev.sh
    - supervisorctl restart dcm-api-service

build jar2:
      stage: build
      only:
        refs:
          - master
      script:
        - sudo cp /data/conf/dcm-prod.conf conf/app.conf
        - sudo /data/sh/dcm/dcm-prod.sh