stages:
  - build

before_script:
  - pwd

cache:
  paths:
    - vendor

build jar:
  stage: build
  only:
    refs:
      - dev
  script:
    - sudo cp /data/conf/dcm-dev.conf conf/app.conf
    - /usr/local/go/bin/go mod tidy &&/usr/local/go/bin/go build -o dcm-api -ldflags "-s -w"
    - supervisorctl restart dcm-api-service