stages:
  - build

before_script:
  - cd cmd/

cache:
  paths:
    - vendor

build jar:
  stage: build
  only:
    refs:
      - dev
  script:
    - cp /data/conf/dcm-dev.conf conf/app.conf
    - /usr/local/go/bin/go mod tidy &&/usr/local/go/bin/go build -o dcm-api